# Generated by Django 4.2.23 on 2026-08-25 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groceries', '0006_groceryorder_razorpay_order_id_and_more'),
        ('delivery', '0004_remove_localdelivery_delivery_exactly_one_order_and_more'),
        ('orders', '0027_order_gps_accuracy_meters_order_gps_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0005_foodsellersettlement_delivery_charge_and_more'),
        ('accounts', '0011_sellerprofile_business_gps_accuracy_meters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('merchandise_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fee_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seller_sponsored_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_mode', models.CharField(choices=[('local', 'Local'), ('delhivery', 'Delhivery'), ('mixed', 'Mixed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CODRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('local_agent', 'Local delivery agent'), ('delhivery', 'Delhivery')], default='local_agent', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('awaiting_collection', 'Awaiting carrier collection'), ('collected', 'Collected by agent/carrier'), ('remitted', 'Remitted to platform'), ('settled', 'Settled'), ('disputed', 'Disputed')], default='collected', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('remitted_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(choices=[('parcel', 'Parcel'), ('food', 'Food'), ('grocery', 'Grocery')], max_length=20)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'Cash on delivery')], max_length=20)),
                ('provider_order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], default='created', max_length=25)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='razorpay', max_length=20)),
                ('event_id', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=80)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerDeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('local', 'Local delivery'), ('delhivery', 'Delhivery')], max_length=20)),
                ('origin_pincode', models.CharField(max_length=6)),
                ('destination_pincode', models.CharField(max_length=6)),
                ('chargeable_weight_grams', models.PositiveIntegerField(default=0)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carrier_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('handling_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quoted_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_collection_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('awb_number', models.CharField(blank=True, max_length=100)),
                ('carrier_status', models.CharField(blank=True, max_length=80)),
                ('manifestation_payload', models.JSONField(blank=True, default=dict)),
                ('quote_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('deducted', 'Deducted'), ('reconciled', 'Reconciled'), ('reversed', 'Reversed')], default='quoted', max_length=20)),
                ('quoted_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('food_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='food.foodorder')),
                ('grocery_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='groceries.groceryorder')),
                ('parcel_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_charges', to='accounts.sellerprofile')),
            ],
            options={
                'ordering': ('-quoted_at',),
            },
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('provider_refund_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('food_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='food.foodorder')),
                ('grocery_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='groceries.groceryorder')),
                ('parcel_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_payment_webhook_event'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='food_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='food.foodorder'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='grocery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='groceries.groceryorder'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='parcel_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codremittance',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cod_remittances', to='delivery.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='codremittance',
            name='delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cod_remittance', to='delivery.localdelivery'),
        ),
        migrations.AddField(
            model_name='codremittance',
            name='food_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='food.foodorder'),
        ),
        migrations.AddField(
            model_name='codremittance',
            name='grocery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='groceries.groceryorder'),
        ),
        migrations.AddField(
            model_name='codremittance',
            name='parcel_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='orders.order'),
        ),
        migrations.AddField(
            model_name='codremittance',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cod_remittances', to='accounts.sellerprofile'),
        ),
        migrations.AddField(
            model_name='chargebreakdown',
            name='food_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='food.foodorder'),
        ),
        migrations.AddField(
            model_name='chargebreakdown',
            name='grocery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='groceries.groceryorder'),
        ),
        migrations.AddField(
            model_name='chargebreakdown',
            name='parcel_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='sellerdeliverycharge',
            constraint=models.UniqueConstraint(condition=models.Q(('parcel_order__isnull', False)), fields=('parcel_order', 'seller'), name='one_parcel_delivery_charge_per_seller'),
        ),
        migrations.AddConstraint(
            model_name='sellerdeliverycharge',
            constraint=models.UniqueConstraint(condition=models.Q(('food_order__isnull', False)), fields=('food_order', 'seller'), name='one_food_delivery_charge_per_seller'),
        ),
        migrations.AddConstraint(
            model_name='sellerdeliverycharge',
            constraint=models.UniqueConstraint(condition=models.Q(('grocery_order__isnull', False)), fields=('grocery_order', 'seller'), name='one_grocery_delivery_charge_per_seller'),
        ),
        migrations.AddConstraint(
            model_name='refundtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_refund_id', ''), _negated=True), fields=('provider_refund_id',), name='unique_provider_refund'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_order_id', ''), _negated=True), fields=('provider_order_id',), name='unique_payment_provider_order'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider_payment_id',), name='unique_payment_provider_payment'),
        ),
        migrations.AddConstraint(
            model_name='codremittance',
            constraint=models.UniqueConstraint(condition=models.Q(('parcel_order__isnull', False), ('seller__isnull', False)), fields=('parcel_order', 'seller'), name='one_cod_remittance_per_parcel_seller'),
        ),
        migrations.AddConstraint(
            model_name='chargebreakdown',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('food_order__isnull', True), ('grocery_order__isnull', True), ('parcel_order__isnull', False)), models.Q(('food_order__isnull', False), ('grocery_order__isnull', True), ('parcel_order__isnull', True)), models.Q(('food_order__isnull', True), ('grocery_order__isnull', False), ('parcel_order__isnull', True)), _connector='OR'), name='charge_breakdown_exactly_one_order'),
        ),
        migrations.AddConstraint(
            model_name='chargebreakdown',
            constraint=models.UniqueConstraint(condition=models.Q(('parcel_order__isnull', False)), fields=('parcel_order',), name='one_breakdown_per_parcel'),
        ),
        migrations.AddConstraint(
            model_name='chargebreakdown',
            constraint=models.UniqueConstraint(condition=models.Q(('food_order__isnull', False)), fields=('food_order',), name='one_breakdown_per_food'),
        ),
        migrations.AddConstraint(
            model_name='chargebreakdown',
            constraint=models.UniqueConstraint(condition=models.Q(('grocery_order__isnull', False)), fields=('grocery_order',), name='one_breakdown_per_grocery'),
        ),
    ]
