# Generated by Django 4.2.23 on 2026-08-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_sellerprofile_business_gps_accuracy_meters_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdeliverycharge',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_charges', to='accounts.sellerprofile'),
        ),
        migrations.AddConstraint(
            model_name='sellerdeliverycharge',
            constraint=models.UniqueConstraint(condition=models.Q(('parcel_order__isnull', False), ('seller__isnull', True)), fields=('parcel_order',), name='one_platform_parcel_delivery_charge'),
        ),
    ]
