# Generated by Django 4.2.23 on 2026-08-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localdelivery',
            name='agent_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='localdelivery',
            name='agent_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='localdelivery',
            name='location_accuracy_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localdelivery',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
