# Generated by Django 4.2.23 on 2026-08-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_gps_accuracy_meters_order_gps_verified_at_and_more'),
        ('accounts', '0011_sellerprofile_business_gps_accuracy_meters_and_more'),
        ('delivery', '0003_localdelivery_customer_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='localdelivery',
            name='delivery_exactly_one_order',
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='payouts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='razorpay_contact_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='razorpay_fund_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='payout_idempotency_key',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='provider_payout_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localdelivery',
            name='collection_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='localdelivery',
            name='parcel_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_deliveries', to='orders.order'),
        ),
        migrations.AddField(
            model_name='localdelivery',
            name='parcel_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_parcel_deliveries', to='accounts.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='deliveryearning',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending COD remittance'), ('payable', 'Payable'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='payable', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='localdelivery',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('food_order__isnull', True), ('grocery_order__isnull', False), ('parcel_order__isnull', True)), models.Q(('food_order__isnull', False), ('grocery_order__isnull', True), ('parcel_order__isnull', True)), models.Q(('food_order__isnull', True), ('grocery_order__isnull', True), ('parcel_order__isnull', False), ('parcel_seller__isnull', False)), _connector='OR'), name='delivery_exactly_one_order'),
        ),
        migrations.AddConstraint(
            model_name='localdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('parcel_order__isnull', False)), fields=('parcel_order', 'parcel_seller'), name='one_local_delivery_per_parcel_seller'),
        ),
    ]
