# Generated by Django 4.2.23 on 2026-09-12 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile_api', '0003_pushdevice_notificationpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCareReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='customer-care/replies/')),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='customercarerequest',
            name='one_open_mobile_request_per_order_type',
        ),
        migrations.AddField(
            model_name='customercarerequest',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='customer-care/'),
        ),
        migrations.AddField(
            model_name='customercarerequest',
            name='order_item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customercarerequest',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='customercarerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('order_id__isnull', False)), fields=('user', 'order_kind', 'order_id', 'request_type'), name='one_open_mobile_request_per_order_type'),
        ),
        migrations.AddField(
            model_name='customercarereply',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mobile_api.customercarerequest'),
        ),
        migrations.AddField(
            model_name='customercarereply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
