# Generated by Django 4.2.23 on 2026-09-13 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0005_backfill_agent_fee'),
        ('accounts', '0011_sellerprofile_business_gps_accuracy_meters_and_more'),
        ('mobile_api', '0004_customercarereply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_kind', models.CharField(max_length=12)),
                ('order_id', models.PositiveIntegerField()),
                ('order_item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('cancellation', 'Cancellation'), ('refund', 'Refund'), ('dispute', 'Dispute')], max_length=20)),
                ('reason', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=500)),
                ('data', models.JSONField(default=dict)),
                ('category', models.CharField(default='order_updates', max_length=30)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('push_status', models.CharField(default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(default='Mobile device', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('failure', 'Failure'), ('dispatch', 'Dispatch')], max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='delivery/proof/')),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_evidence', to='delivery.localdelivery')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sellercase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'reviewing'))), fields=('seller', 'order_kind', 'order_id', 'kind'), name='one_active_seller_case'),
        ),
    ]
