# Generated by Django 4.2.23 on 2026-09-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0005_sellercase_notification_devicesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_api.devicesession'),
        ),
    ]
