# Generated by Django 4.2.23 on 2026-09-14 03:39

from django.db import migrations, models
import django.db.models.deletion
import mobile_api.storage


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_sellerdeliverycharge_seller_and_more'),
        ('mobile_api', '0006_pushdevice_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercase',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellercase',
            name='refund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.refundtransaction'),
        ),
        migrations.AlterField(
            model_name='deliveryevidence',
            name='photo',
            field=models.ImageField(blank=True, storage=mobile_api.storage.PrivateEvidenceStorage(), upload_to='delivery/proof/'),
        ),
    ]
