# Generated by Django 4.2.23 on 2026-09-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0008_pushreceipt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sellercase',
            name='one_active_seller_case',
        ),
        migrations.AddConstraint(
            model_name='sellercase',
            constraint=models.UniqueConstraint(condition=models.Q(('order_item_id__isnull', False), ('status__in', ('open', 'reviewing'))), fields=('seller', 'order_kind', 'order_id', 'order_item_id', 'kind'), name='one_active_seller_item_case'),
        ),
        migrations.AddConstraint(
            model_name='sellercase',
            constraint=models.UniqueConstraint(condition=models.Q(('order_item_id__isnull', True), ('status__in', ('open', 'reviewing'))), fields=('seller', 'order_kind', 'order_id', 'kind'), name='one_active_seller_order_case'),
        ),
    ]
