# Generated by Django 4.2.23 on 2026-08-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='business_gps_accuracy_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_gps_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='delhivery_pickup_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
