# Generated by Django 5.2.17 on 2026-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sellerprofile_business_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/covers/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/logos/'),
        ),
    ]
