# Generated by Django 4.2.23 on 2026-08-25 02:40

from django.db import migrations, models


def make_service_areas_local(apps, schema_editor):
    apps.get_model('groceries', 'GroceryServiceArea').objects.update(delivery_mode='local')


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_seed_categories'),
    ]

    operations = [
        migrations.RunPython(make_service_areas_local, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='groceryorder',
            name='delivery_mode',
            field=models.CharField(choices=[('local', 'ZIYAMART local delivery agent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='groceryservicearea',
            name='delivery_mode',
            field=models.CharField(choices=[('local', 'ZIYAMART local delivery agent')], default='local', max_length=20),
        ),
    ]
