# Generated by Django 4.2.23 on 2026-08-25 02:42

import django.core.validators
from django.db import migrations, models


def backfill_store_pincodes(apps, schema_editor):
    Store = apps.get_model('groceries', 'GroceryStore')
    for store in Store.objects.prefetch_related('service_areas'):
        area = store.service_areas.filter(is_active=True, delivery_mode='local').order_by('pincode').first()
        if area:
            store.pincode = area.pincode
            store.save(update_fields=['pincode'])


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_alter_groceryorder_delivery_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerystore',
            name='pincode',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
        migrations.RunPython(backfill_store_pincodes, migrations.RunPython.noop),
    ]
