# Generated by Django 4.2.23 on 2026-08-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0004_grocerystore_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryorder',
            name='gps_accuracy_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryorder',
            name='gps_verified_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryorder',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='groceryorder',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='grocerystore',
            name='gps_accuracy_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grocerystore',
            name='gps_verified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grocerystore',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='grocerystore',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
