# Generated by Django 4.2.23 on 2026-07-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
