# Generated by Django 4.2.23 on 2026-07-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_supportreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
