# Generated by Django 4.2.23 on 2026-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_supportticket_admin_note_supportticket_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='last_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
