# Generated by Django 4.2.23 on 2026-07-10 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0021_order_refund_amount_order_refund_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('Order Placed', 'Order Placed'), ('Payment Verified', 'Payment Verified'), ('Payment Failed', 'Payment Failed'), ('Order Confirmed', 'Order Confirmed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Return Approved', 'Return Approved'), ('Return Rejected', 'Return Rejected'), ('Return Picked Up', 'Return Picked Up'), ('Returned', 'Returned'), ('Refund Initiated', 'Refund Initiated'), ('Refund Completed', 'Refund Completed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='orders.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
