# Generated by Django 4.2.23 on 2026-07-12 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_ordertimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.orderitem'),
        ),
    ]
