from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


def add_initial_area(apps, schema_editor):
    apps.get_model("food", "FoodServiceArea").objects.get_or_create(
        pincode="243638", defaults={"city": "Sahaswan", "is_active": True}
    )


class Migration(migrations.Migration):
    initial = True
    dependencies = [("accounts", "0008_seller_ai_credits"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="FoodServiceArea", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("pincode", models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator("^\\d{6}$", "Enter a valid 6-digit pincode.")])), ("city", models.CharField(blank=True, max_length=80)), ("is_active", models.BooleanField(default=True))], options={"ordering": ("pincode",)}),
        migrations.CreateModel(name="Restaurant", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150)), ("slug", models.SlugField(blank=True, max_length=180, unique=True)), ("description", models.TextField(blank=True)), ("image", models.ImageField(blank=True, null=True, upload_to="restaurants/")), ("cuisine", models.CharField(blank=True, max_length=150)), ("preparation_minutes", models.PositiveSmallIntegerField(default=30)), ("minimum_order", models.DecimalField(decimal_places=2, default=0, max_digits=8)), ("delivery_fee", models.DecimalField(decimal_places=2, default=0, max_digits=8)), ("accepts_orders", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("seller", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="restaurant", to="accounts.sellerprofile")), ("service_areas", models.ManyToManyField(blank=True, related_name="restaurants", to="food.foodservicearea"))]),
        migrations.CreateModel(name="MenuSection", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100)), ("display_order", models.PositiveSmallIntegerField(default=0)), ("restaurant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="food.restaurant"))], options={"ordering": ("display_order", "name"), "unique_together": {("restaurant", "name")}}),
        migrations.CreateModel(name="MenuItem", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=160)), ("description", models.TextField(blank=True)), ("image", models.ImageField(blank=True, null=True, upload_to="food/menu/")), ("food_type", models.CharField(choices=[("veg", "Vegetarian"), ("non_veg", "Non-vegetarian"), ("egg", "Contains egg")], default="veg", max_length=10)), ("is_available", models.BooleanField(default=True)), ("accepts_notes", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("restaurant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="menu_items", to="food.restaurant")), ("section", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="food.menusection"))], options={"ordering": ("section__display_order", "name")}),
        migrations.CreateModel(name="MenuItemOption", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(default="Regular", max_length=50)), ("price", models.DecimalField(decimal_places=2, max_digits=8)), ("is_available", models.BooleanField(default=True)), ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="options", to="food.menuitem"))], options={"ordering": ("price", "id"), "unique_together": {("item", "name")}}),
        migrations.CreateModel(name="FoodOrder", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("full_name", models.CharField(max_length=120)), ("phone", models.CharField(max_length=15)), ("address", models.TextField()), ("city", models.CharField(max_length=80)), ("state", models.CharField(max_length=80)), ("pincode", models.CharField(max_length=6)), ("include_cutlery", models.BooleanField(default=False)), ("delivery_note", models.CharField(blank=True, max_length=300)), ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)), ("delivery_fee", models.DecimalField(decimal_places=2, default=0, max_digits=8)), ("total", models.DecimalField(decimal_places=2, max_digits=10)), ("payment_method", models.CharField(choices=[("cod", "Cash on delivery"), ("online", "Online payment")], default="cod", max_length=10)), ("payment_status", models.CharField(default="Pending", max_length=20)), ("status", models.CharField(choices=[("placed", "Placed"), ("accepted", "Accepted"), ("preparing", "Preparing"), ("ready", "Ready for delivery"), ("out_for_delivery", "Out for delivery"), ("delivered", "Delivered"), ("cancelled", "Cancelled")], default="placed", max_length=30)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("restaurant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="food.restaurant")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="food_orders", to=settings.AUTH_USER_MODEL))], options={"ordering": ("-created_at",)}),
        migrations.CreateModel(name="FoodOrderItem", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("item_name", models.CharField(max_length=160)), ("option_name", models.CharField(max_length=50)), ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)), ("quantity", models.PositiveSmallIntegerField(default=1)), ("customer_note", models.CharField(blank=True, max_length=300)), ("menu_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="food.menuitem")), ("option", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="food.menuitemoption")), ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="food.foodorder"))]),
        migrations.RunPython(add_initial_area, migrations.RunPython.noop),
    ]
