# Generated by Django 4.2.23 on 2026-08-25 02:42

import django.core.validators
from django.db import migrations, models


def backfill_restaurant_pincodes(apps, schema_editor):
    Restaurant = apps.get_model('food', 'Restaurant')
    for restaurant in Restaurant.objects.prefetch_related('service_areas'):
        area = restaurant.service_areas.filter(is_active=True).order_by('pincode').first()
        if area:
            restaurant.pincode = area.pincode
            restaurant.save(update_fields=['pincode'])


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_payouts_and_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pincode',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit pincode.')]),
        ),
        migrations.RunPython(backfill_restaurant_pincodes, migrations.RunPython.noop),
    ]
