# Generated by Django 4.2.23 on 2026-08-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodorder_gps_accuracy_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsellersettlement',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='foodsellersettlement',
            name='tcs_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
