# Generated by Django 4.2.23 on 2026-05-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, help_text="Store size options as a JSON list, e.g. ['S','M','L','XL']", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('jeans', 'Jeans'), ('shoes', 'Shoes'), ('dress', 'Dress'), ('kidswear', 'Kidswear'), ('accessory', 'Accessory')], default='shirt', max_length=50),
        ),
    ]
