# Generated by Django 4.2.23 on 2026-06-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list, help_text="Store size options as a JSON list, e.g. ['S','M','L','XL']"),
        ),
    ]
