# Generated by Django 4.2.23 on 2026-06-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productcolor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image shown when this color is selected.', null=True, upload_to='products/colors/'),
        ),
    ]
