# Generated by Django 4.2.23 on 2026-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(help_text='Example: S, M, L, XL, XXL, 30, 32, Free Size', max_length=30),
        ),
    ]
