# Generated by Django 4.2.23 on 2026-07-14 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productvariant_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Leave empty if this image is common for all colors.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.productcolor'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Images with lower numbers appear first.'),
        ),
    ]
