# Generated by Django 4.2.23 on 2026-08-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_moderation_catalogrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text='GST percentage applied to the seller price for this product.', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='package_height_cm',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='package_length_cm',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='package_weight_grams',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='product',
            name='package_width_cm',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=7),
        ),
    ]
