from django.urls import include, path

from . import views
from . import customer_orders
from .payment_api import NativePaymentView
from .operations_api import InboxView, SessionsView, RiderEvidenceView, SellerCasesView


urlpatterns = [
    path("orders/<str:kind>/<int:pk>/payment/", NativePaymentView.as_view()),
    path("account/sessions/", SessionsView.as_view()),
    path("account/sessions/<int:pk>/", SessionsView.as_view()),
    path("notifications/", InboxView.as_view()),
    path("notifications/<int:pk>/", InboxView.as_view()),
    path("partners/rider/jobs/<int:pk>/evidence/", RiderEvidenceView.as_view()),
    path("partners/seller/<str:kind>/orders/<int:pk>/cases/", SellerCasesView.as_view()),
    path("order-items/<int:pk>/review/", customer_orders.ItemReviewView.as_view()),
    path("orders/shop/<int:pk>/returns/", customer_orders.OrderReturnsView.as_view()),
    path("orders/<str:kind>/<int:pk>/experience/", customer_orders.OrderExperienceView.as_view()),
    path("orders/<str:kind>/<int:pk>/invoice/", customer_orders.OrderInvoiceView.as_view()),
    path("partners/", include("mobile_api.partner_urls")),
    path("auth/signup/", views.SignupView.as_view(), name="mobile-signup"),
    path("auth/verify-otp/", views.VerifyOTPView.as_view(), name="mobile-verify-otp"),
    path("auth/resend-otp/", views.ResendSignupOTPView.as_view(), name="mobile-resend-otp"),
    path("auth/login/", views.LoginView.as_view(), name="mobile-login"),
    path("auth/password/reset/request/", views.PasswordResetRequestView.as_view(), name="mobile-password-reset-request"),
    path("auth/password/reset/confirm/", views.PasswordResetConfirmView.as_view(), name="mobile-password-reset-confirm"),
    path("auth/password/change/", views.ChangePasswordView.as_view(), name="mobile-password-change"),
    path("auth/logout/", views.LogoutView.as_view(), name="mobile-logout"),
    path("account/profile/", views.ProfileView.as_view(), name="mobile-profile"),
    path("account/notifications/", views.NotificationPreferenceView.as_view(), name="mobile-notification-preferences"),
    path("account/push-devices/", views.PushDeviceView.as_view(), name="mobile-push-device"),
    path("account/delete-request/", views.AccountDeletionRequestView.as_view(), name="mobile-account-delete-request"),
    path("categories/", views.CategoryListView.as_view(), name="mobile-categories"),
    path("products/", views.ProductListView.as_view(), name="mobile-products"),
    path("products/<slug:slug>/", views.ProductDetailView.as_view(), name="mobile-product-detail"),
    path("wishlist/", views.WishlistView.as_view(), name="mobile-wishlist"),
    path("wishlist/<int:product_id>/", views.WishlistItemView.as_view(), name="mobile-wishlist-item"),
    path("cart/", views.CartView.as_view(), name="mobile-cart"),
    path("cart/items/", views.CartItemCreateView.as_view(), name="mobile-cart-add"),
    path("cart/items/<int:item_id>/", views.CartItemView.as_view(), name="mobile-cart-item"),
    path("addresses/", views.AddressListCreateView.as_view(), name="mobile-addresses"),
    path("addresses/<int:pk>/", views.AddressDetailView.as_view(), name="mobile-address-detail"),
    path("addresses/<int:pk>/default/", views.DefaultAddressView.as_view(), name="mobile-address-default"),
    path("food/restaurants/", views.RestaurantListView.as_view(), name="mobile-restaurants"),
    path("food/restaurants/<slug:slug>/", views.RestaurantDetailView.as_view(), name="mobile-restaurant-detail"),
    path("food/cart/", views.FoodCartView.as_view(), name="mobile-food-cart"),
    path("food/cart/items/", views.FoodCartItemCreateView.as_view(), name="mobile-food-cart-add"),
    path("food/cart/items/<int:item_id>/", views.FoodCartItemView.as_view(), name="mobile-food-cart-item"),
    path("groceries/stores/", views.GroceryStoreListView.as_view(), name="mobile-grocery-stores"),
    path("groceries/stores/<slug:slug>/", views.GroceryStoreDetailView.as_view(), name="mobile-grocery-store-detail"),
    path("groceries/categories/", views.GroceryCategoryListView.as_view(), name="mobile-grocery-categories"),
    path("groceries/products/", views.GroceryProductListView.as_view(), name="mobile-grocery-products"),
    path("groceries/cart/", views.GroceryCartView.as_view(), name="mobile-grocery-cart"),
    path("groceries/cart/items/", views.GroceryCartItemCreateView.as_view(), name="mobile-grocery-cart-add"),
    path("groceries/cart/items/<int:item_id>/", views.GroceryCartItemView.as_view(), name="mobile-grocery-cart-item"),
    path("checkout/shop/", views.ParcelCheckoutView.as_view(), name="mobile-shop-checkout"),
    path("checkout/<str:kind>/quote/", views.CheckoutQuoteView.as_view(), name="mobile-checkout-quote"),
    path("checkout/food/", views.FoodCheckoutView.as_view(), name="mobile-food-checkout"),
    path("checkout/grocery/", views.GroceryCheckoutView.as_view(), name="mobile-grocery-checkout"),
    path("orders/", views.OrderListView.as_view(), name="mobile-orders"),
    path("orders/<int:pk>/", views.OrderDetailView.as_view(), name="mobile-order-detail"),
    path("orders/<str:kind>/<int:order_id>/cancel/", views.OrderCancelView.as_view(), name="mobile-order-cancel"),
    path("orders/<str:kind>/<int:order_id>/care/", views.OrderCareRequestView.as_view(), name="mobile-order-care"),
    path("support/", views.CustomerCareListCreateView.as_view(), name="mobile-support"),
    path("support/<int:pk>/replies/", views.CustomerCareReplyView.as_view(), name="mobile-support-reply"),
]
